apiVersion: apps/v1
kind: Deployment 
metadata:
  name: html-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-page
  template:
    metadata:
      labels:
        app: html-page
    spec:
      containers:
        - name: nginx
          image: html-page
          ports:
          - containerPort: 3000